### ISSUE TITLE
Installation instructions for less familiar?

### ISSUE THREAD

**Issue by jrsteensen** [blha303/gitlab-discord-bridge#3]
Hey there! Just was curious if you could add verbose installation instructions for those of us who aren't too familiar with installing this sort of thing. Seem like it would be EXACTLY what I need.

**Comment by blha303** [comment]
Is this enough detail? :)

**Comment by jrsteensen** [comment]
Perfect! Thank you. I did just discover a workaround using the slack messaging webapp from GitLab to Discord that seems to work 99% as well, but definitely going to test this. Thank you very much!

**Comment by jrsteensen** [comment]
Works perfect. Thank you for the quick turnaround.
