### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by avluis** [blha303/gitlab-discord-bridge#4]
Do you mind if I turn this into a container -- as well as making it available publicly?

I can do a pull request once I confirm everything is working if interested.
[Here](https://github.com/avluis/iroffer) is an [example](https://hub.docker.com/r/avluis/iroffer/) of my (public) work.

**Comment by blha303** [comment]
Be my guest :)

**Comment by avluis** [comment]
Here is my [work so far](https://github.com/avluis/gitlab-discord-bridge/commit/ff4f049e000793dcc07bb187ad98328b9c49f95b).
I've been sick so things are taking a bit longer than anticipated 😷

It's still a bit rough around the edges:
- The config file needs to be mounted before running or it will error out
- There are no usage instructions yet

Will be testing the image, as well as putting the instructions together within the next few days.

**Comment by avluis** [comment]
Forgot to ask;

Do you want me to handle maintaining the image and how it is linked to Docker Hub from my repo or will you prefer for it be available under your name (which would mean setting up a Docker Hub account for this repo).

It's up to you how you want to do this but it does look better if the official repo was used alongside Docker Hub (but not a requirement -- just means maintaining two repos).
As soon as I get your reply then I can work on the documentation as it requires the appropriate urls.

**Comment by blha303** [comment]
I'm really not fussed either way, I'm not likely to use the Docker image myself. It's entirely up to you, I'll add the link to the README when it's up so people know it's there

**Comment by avluis** [comment]
Got it~ I'll go ahead and take of maintaining my fork current with yours then (with Docker support).
I'll make sure my fork has links back to yours as well!

**Comment by TTVCloudyYT** [comment]
bro this shit is fake as fuck it will legit raid your discord server
