### ISSUE TITLE
Bot wont send messages or show as online

### ISSUE THREAD

**Issue by haloman30** [blha303/gitlab-discord-bridge#8]
In terminal, the request seems to go through without a problem, but I see nothing happening in the text channel nor does the bot show as online.

Not sure what to do at this point

**Comment by haloman30** [comment]
Never mind it just doesn't work with system hooks

**Comment by blha303** [comment]
The bot won't show as online because it uses API requests to send messages as the bot user. You can make the bot user appear online using phony.py from the repository. Try testing the webhook from gitlab to see if the bot is functioning.

**Comment by haloman30** [comment]
That's what I've been doing with it, testing via gitlab. It says it had an HTTP 200 and went fine, and the actual bot in SSH appears to have no error either.

[![Screenshot from Gyazo](https://gyazo.com/45407c2b660b0f58958e9108d44c2a18/raw)](https://gyazo.com/45407c2b660b0f58958e9108d44c2a18)

```
:round_pushpin: <gitlab url censored>
**haloman30** pushed 3 commits:
`cad6dc9` **haloman30**: Update README.md
`69d1f4d` **haloman30**: Fixed screenshots and added 'Open Game Dir'

Fixed the screenshot function at last (wont work while debugging in VS for some reason), and got the 'Open Game Dir' to work.
`1444d22` **haloman30**: imgui

yes
<ip censored> - - [04/Oct/2017 23:25:29] "POST /<channel id censored> HTTP/1.1" 200 -
```

The token in config.json is set to the bot user's token.

**Comment by haloman30** [comment]
Okay uh well...

It started working with no real explanation.

My only theory is that maybe the fact that the gitlab I am working with has its own host (aka not gitlab.com) and maybe was cached badly or something, I really don't have a clue at this point.

Sort of relevant, I was trying to get it to work with a System hook earlier but it kept throwing out HTTP error 500 at me. Is the bot just not designed to work as a system hook? Or is that a bug that I should give you more info about?

**Comment by blha303** [comment]
To be honest I have no clue, I don't use Gitlab myself, I made this for an organization I'm involved in that ended up not using this at all. I don't have a setup for testing it or even checking bugs. I appreciate bug reports but I can't do anything about them at this point. Thanks for the report.

**Comment by blha303** [comment]
Issue not fixed, leaving open until confirmed

**Comment by haloman30** [comment]
The issue I had is indeed fixed at this point, been going strong since last night. Not sure what caused it but I suspect it was something on my gitlab's end. If that's the issue you're referring to and not the one about system hooks, feel free to call it closed. Otherwise just reopen I suppose
