### ISSUE TITLE
Running via gunicorn doesn't initialize config

### ISSUE THREAD

**Issue by tomastillery** [blha303/gitlab-discord-bridge#9]
If backgrounding via gunicorn (per [README.md](https://github.com/blha303/gitlab-discord-bridge/blob/master/README.md)) the `config` dict is never initialized, causing exceptions when referencing it in handlers. Because the variable shadows the built-in `config` module, the exception is a non-intuitive exception that you can't subscript a `module`.

**Comment by blha303** [comment]
Hm, how did I miss that. Thanks for pointing it out, I've pushed a change to hopefully fix this, please let me know if it doesn't.
